# --------------------
# Base
# --------------------
FROM node:22.15-bullseye AS base

WORKDIR /usr/src/app

COPY package*.json ./

# --------------------
# Development
# --------------------
FROM base AS dev

RUN mkdir -p /usr/src/app/node_modules \
    && chown -R node:node /usr/src/app
    
USER node

RUN  npm install

CMD ["npm", "run", "dev"]

# --------------------
# Build (production build)
# --------------------
FROM base AS build

RUN npm ci

COPY src ./src
COPY public ./public
COPY tsconfig.json tsconfig.app.json tsconfig.node.json vite.config.ts index.html ./

RUN npm run build

# --------------------
# Runtime (nginx)
# --------------------
FROM nginx:alpine

COPY --from=build /usr/src/app/dist /usr/share/nginx/html

COPY nginx.conf /etc/nginx/nginx.conf

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
