FROM node:22.15-bullseye AS base

WORKDIR /usr/src/app

USER root

COPY package*.json ./

# dev docker image 
FROM base AS dev

RUN --mount=type=cache,target=/usr/src/app/.npm \
  npm set cache /usr/src/app/.npm && \
  npm install

RUN chown -R node:node /usr/src/app/node_modules

USER node

CMD ["npm", "run", "dev"]

# production docker image 
FROM base AS prod

RUN npm ci --only=production

COPY src ./src
COPY index.html ./

USER node

RUN npm run build

FROM nginx:alpine 

COPY --from=prod /usr/src/app/dist /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]